### ISSUE TITLE
Move wrap-env from pathom3 demo into xtdb. Remove pathom2 dependency.

### ISSUE THREAD

**Issue by awkay** [roterski/fulcro-rad-xtdb#5]
Hi there.

I've released new versions of all of the RAD stuff, and made a `pathom3` branch on the demo. I did the porting work there for xtdb (you'll see a new `wrap-env` in the parser ns). It would be good to move that function into your library, instead of it just being in the demo.

Also, you should try to remove all references to Pathom 2 in your library. This should be trivial (I did it already in the RAD datomic plugin and in RAD itself), and is backwards compatible. Pathom 2 plugins, resolvers, and mutations are just maps, so all I had to do was turn any calls to defmutation/defresolver into defs of maps. Just use a REPL to view them when running with Pathom 2.  You have to, of course, manually spell out the full pathom 2 namespaces on the keywords.

This will allow people to only have one version of Pathom on the classpath, which will confuse them less when using autocomplete, etc.

**Comment by roterski** [comment]
resolved with https://github.com/roterski/fulcro-rad-xtdb/pull/6
